module.exports = {
  READY: "READY",
  WAITING: "WAITING",
  ID: "ID",
  IMAGE: "IMAGE",
  HOST: "HOST",
  PHASE_UPDATE: "PHASE_UPDATE",
  PLAYER_ORDER: "PLAYER_ORDER",
  IS_TRAITOR: "IS_TRAITOR",
  ALLIES: "ALLIES",
  MISSION_SUGGESTION: "MISSION_SUGGESTION",
  MISSION_VOTE: "MISSION_VOTE",
  MISSION_LEADER: "MISSION_LEADER",
  MISSION_PLAYERS: "MISSION_PLAYERS",
  MISSION_DECISION: "MISSION_DECISION",
  SCORE: "SCORE",
  ROUND: "ROUND",
  ROUNDS: "ROUNDS"
};
